<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Michael D. Garber, PhD MPH" />


<title>R for data wrangling 1: learning the ground rules of dplyr with publicly available COVID-19 data</title>

<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="https://michaeldgarber.github.io/">
    <span class="fa fa-home"></span>
     
    MDG
  </a>
</li>
<li>
  <a href="index.html">R course</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">R for data wrangling 1: learning the ground rules of dplyr with publicly available COVID-19 data</h1>
<h4 class="author">Michael D. Garber, PhD MPH</h4>
<h4 class="date">Revised August 4, 2022</h4>

</div>


<div id="outline" class="section level1" number="1">
<h1><span class="header-section-number">1</span> Outline</h1>
<ol style="list-style-type: decimal">
<li>Introduction and pre-requisites</li>
<li>Install packages and download the data</li>
<li>Explore the NYT state COVID-19 data using dplyr</li>
</ol>
</div>
<div id="introduction-and-pre-requisites" class="section level1" number="2">
<h1><span class="header-section-number">2</span> Introduction and pre-requisites</h1>
<div id="purpose" class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> Purpose</h2>
<p>The purpose of this tutorial is to learn the basics of dplyr in the context of an applied example with publicly available COVID-19 data from The New York Times.</p>
</div>
<div id="target-audience" class="section level2" number="2.2">
<h2><span class="header-section-number">2.2</span> Target audience</h2>
<p>The target audience for this demo is someone with little to no experience using R. I will also assume no experience with any statistical programming language, although some experience with SAS or STATA would certainly not hurt. I imagine the target audience will have familiarity with the basics of data management in a spreadsheet-based program like Excel and may want to try using a programming-oriented tool for data management. For an excellent overview of why it can be preferable to analyze and manage data with a programming language rather than spreadsheet tools, please see the preliminary module of this series (<a href="https://michaeldgarber.github.io/teach-r/0-pre-reqs" class="uri">https://michaeldgarber.github.io/teach-r/0-pre-reqs</a>) or this great <a href="https://www.jessesadler.com/post/excel-vs-r/">blog post</a> by Jesse Adler.</p>
</div>
<div id="what-is-dplyr" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> What is dplyr?</h2>
<p><a href="https://dplyr.tidyverse.org/">Dplyr</a> is a set of functions for managing and manipulating data in R. As stated on the webpage:</p>
<blockquote>
<p>“dplyr is a grammar of data manipulation, providing a consistent set of verbs that help you solve the most common data manipulation challenges.”</p>
</blockquote>
<p>There are several ways to manage data in R, including <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/00Index.html">base R</a>. I focus here on dplyr because it’s widely used and, I think, intuitive. Dplyr is part of the larger collection of packages called the <a href="https://www.tidyverse.org/">tidyverse</a>, which includes other popular packages like ggplot2. One advantage of dplyr is that, when combined with the pipe operator (explained below), it is quite human readable. Like good writing , it emphasizes the verbs (Zinsser, On Writing Well, Chapter 10).</p>
</div>
<div id="the-goal-of-this-tutorial" class="section level2" number="2.4">
<h2><span class="header-section-number">2.4</span> The goal of this tutorial</h2>
<p>The goal of this tutorial is to illustrate the basics of dplyr using publicly available data on COVID-19 incidence posted by <a href="https://github.com/nytimes/covid-19-data">The New York Times</a>.</p>
</div>
<div id="prerequisites" class="section level2" number="2.5">
<h2><span class="header-section-number">2.5</span> Prerequisites</h2>
<ol style="list-style-type: decimal">
<li>R and RStudio are installed.</li>
</ol>
<p>As a <a href="https://michaeldgarber.github.io/teach-r/0-pre-reqs">reminder</a>:</p>
<ul>
<li>To download R, go to CRAN and download R from the location nearest you: <a href="https://cran.r-project.org/mirrors.html" class="uri">https://cran.r-project.org/mirrors.html</a>.</li>
<li>Then, install RStudio Desktop (the free version) at this link: <a href="https://rstudio.com/products/rstudio/download" class="uri">https://rstudio.com/products/rstudio/download</a> .</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>You’re familiar with how to use the RStudio interface</li>
</ol>
<p><img src="images/script-screenshot.PNG" width="958" /></p>
<ol start="3" style="list-style-type: decimal">
<li><strong>Explore resources on dplyr.</strong> Finally, although we’ll cover the basics of <em>dplyr</em> here, you might peruse some of the excellent existing material on dplyr:</li>
</ol>
<ul>
<li><a href="https://dplyr.tidyverse.org/" class="uri">https://dplyr.tidyverse.org/</a> - The main webpage contains a short overview of the package and describes the key functions, aka verbs, as we will also do here.</li>
<li><a href="https://dplyr.tidyverse.org/articles/dplyr.html" class="uri">https://dplyr.tidyverse.org/articles/dplyr.html</a> - The vignette expands upon the main landing page with some examples.</li>
<li><a href="https://r4ds.had.co.nz/transform.html" class="uri">https://r4ds.had.co.nz/transform.html</a> - This <a href="https://r4ds.had.co.nz/">book</a> by Wickham and Grolemund is the authoritative guide to learning the tidyverse. The chapter on <a href="https://r4ds.had.co.nz/transform.html">data transformation</a> chapter covers dplyr, specifically.</li>
</ul>
</div>
</div>
<div id="install-packages-and-download-the-data" class="section level1" number="3">
<h1><span class="header-section-number">3</span> Install packages and download the data</h1>
<div id="install-and-load-packages" class="section level2" number="3.1">
<h2><span class="header-section-number">3.1</span> Install and load packages</h2>
<p>Now that we have RStudio installed and up and running, our first step is to install packages, the basics of which we described in the <a href="https://michaeldgarber.github.io/teach-r/0-pre-reqs">previous module</a>.</p>
<pre class="r"><code>install.packages(&quot;tidyverse&quot;)</code></pre>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
## ✔ ggplot2 3.3.6     ✔ purrr   0.3.4
## ✔ tibble  3.1.8     ✔ dplyr   1.0.9
## ✔ tidyr   1.2.0     ✔ stringr 1.4.0
## ✔ readr   2.1.2     ✔ forcats 0.5.1
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div id="load-the-covid-19-data-from-the-new-york-times" class="section level2" number="3.2">
<h2><span class="header-section-number">3.2</span> Load the COVID-19 data from <em>The New York Times</em></h2>
<p>For this example, we will use COVID-19 data from <a href="https://github.com/nytimes/covid-19-data">The New York Times’ GitHub repository</a>. There are a few datasets available at varying geographic scales. Let’s use their state-level dataset. The data include the number of cumulative cases and the number of cumulative deaths by state and day, beginning January 21, 2020.</p>
<p>We’ll load the data two ways, hoping at least one of them works.</p>
<div id="load-the-data-directly-from-their-github-repository" class="section level3" number="3.2.1">
<h3><span class="header-section-number">3.2.1</span> Load the data directly from their Github repository</h3>
<p>First, let’s try the fancy way, loading it directly from GitHub. Below, the first line of code defines an object, <code>nyt_state_url</code> to be the URL where the NYT data are located. The second line of code uses a base R function, <code>url()</code>, to parse that URL as a CSV. We then convert it from a CSV to an R object using <code>read_csv()</code>. <code>read_csv()</code> is a function in <em>readr</em>, another package in the <strong>tidyverse.</strong> Accordingly, the resulting output of these few lines of code will be a <a href="https://r4ds.had.co.nz/tibbles.html"><strong>tibble</strong></a>, tidyverse speak for a “tidy table.” Basically, a tibble is a table, or data frame, with some opinionated formatting advantages that make it easy to work with.</p>
<p>Of note, the code below includes our first use of the <code>%&gt;%</code> (read: <a href="https://magrittr.tidyverse.org/reference/pipe.html">pipe</a>) operator. The pipe operator is part of the <strong>magrittr</strong> package and is a key element of the tidyverse. The pipe separates the action-oriented functions, <code>read_csv()</code> and <code>url()</code> from the object, <code>nyt_state_url</code>. In my opinion, this separation makes it easier to read, as I’ll discuss more in the next section.</p>
<p>Another side-note: I use the equals sign, <code>=</code>, when assigning new objects, because I think it’s easier to read type than R’s <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/assignOps.html">traditional assignment operator</a>, <code>&lt;-</code>. I’ve heard <code>&lt;-</code> has advantages, but I’ve never had an issue using <code>=</code>.</p>
<pre class="r"><code>nyt_state_url = &quot;https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv&quot;

nyt_state_data = nyt_state_url %&gt;% 
  url() %&gt;% 
  read_csv()</code></pre>
<pre><code>## Rows: 48838 Columns: 5
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr  (2): state, fips
## dbl  (2): cases, deaths
## date (1): date
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<p>An alternative, equivalent, way to write that code is use the traditional nested parentheses. The nested parentheses aren’t so bad when just a few functions are used, but, as the number of functions increases, the nested parentheses become difficult to read.</p>
<pre class="r"><code>nyt_state_url = &quot;https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv&quot;
nyt_state_data = read_csv(url(nyt_state_url))</code></pre>
<p>Either way we write it, we get a resulting dataset, <code>nyt_state_data</code>, which should be visible in the “Environment” pane of RStudio. It tells us that the data have 48,838 observations and 5 variables. (Again, I called this dataset on August 2, 2022; the number of observations will be higher in the future.)</p>
<p><img src="images/module-1-nyt-data-environment-screenshot.png" width="500" /></p>
<p>As noted above, <code>read_csv()</code> is part of the <strong>readr</strong> package and returns a “<a href="https://r4ds.had.co.nz/tibbles.html">tibble</a>”. One benefit of using tibbles, as noted <a href="https://r4ds.had.co.nz/tibbles.html">here</a>, is that they can be printed without overwhelming the console. (This is not necessarily true of data frames more generally).</p>
<p>Let’s first confirm that <code>nyt_state_data</code> is a tibble using the base-R <code>class()</code> function, which returns the object’s class. The tibble object class is indicated by <code>tbl_df</code>. And then we can print the tibble by typing its name to get a sense of its dimensions (rows and columns) and what the variables look like.</p>
<p>At this writing, there are 48,838 observations and 5 columns. The variable type is denoted below the variable names.</p>
<p>We can also use the <code>class()</code> function from base R to return the type for a single column. The <code>$</code> is a base-R function that <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/Extract">extracts</a> an element of an object by name.</p>
<pre class="r"><code>class(nyt_state_data) #what type of object is it?</code></pre>
<pre><code>## [1] &quot;spec_tbl_df&quot; &quot;tbl_df&quot;      &quot;tbl&quot;         &quot;data.frame&quot;</code></pre>
<pre class="r"><code>nyt_state_data #print the tibble</code></pre>
<pre><code>## # A tibble: 48,838 × 5
##    date       state      fips  cases deaths
##    &lt;date&gt;     &lt;chr&gt;      &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;
##  1 2020-01-21 Washington 53        1      0
##  2 2020-01-22 Washington 53        1      0
##  3 2020-01-23 Washington 53        1      0
##  4 2020-01-24 Illinois   17        1      0
##  5 2020-01-24 Washington 53        1      0
##  6 2020-01-25 California 06        1      0
##  7 2020-01-25 Illinois   17        1      0
##  8 2020-01-25 Washington 53        1      0
##  9 2020-01-26 Arizona    04        1      0
## 10 2020-01-26 California 06        2      0
## # … with 48,828 more rows
## # ℹ Use `print(n = ...)` to see more rows</code></pre>
<pre class="r"><code>class(nyt_state_data$state) #character</code></pre>
<pre><code>## [1] &quot;character&quot;</code></pre>
</div>
<div id="download-the-data-i-saved-and-read-into-r-using-read_csv" class="section level3" number="3.2.2">
<h3><span class="header-section-number">3.2.2</span> Download the data I saved and read into R using <code>read_csv()</code></h3>
<p>If the direct call to NYT GitHub didn’t work, here’s a back-up way that should work to read the data into R. On August 2, 2022, I downloaded the data as a CSV. The file is called <code>nyt_state_data_downloaded.csv</code> in this Dropbox <a href="https://www.dropbox.com/sh/ff85l058vl82wwy/AABKygH3PhQkausaxOcIgO0Sa?dl=0">folder</a>.</p>
<p>If needed, download the CSV and save locally to your computer. I would suggest saving to a sub-folder of this project, e.g., called “data-input”.</p>
<p>Then, use <code>read_csv()</code> to <a href="https://r4ds.had.co.nz/data-import.html">import</a> the csv into R. As discussed in the <a href="https://michaeldgarber.github.io/teach-r/0-pre-reqs">last module</a>, we can use the here package for this. So, if the .csv is in a folder in this project directory called, “data-input”, then this code should work to read it in:</p>
<pre class="r"><code>library(here)
setwd(here(&quot;data-input&quot;))
nyt_state_data = read_csv(&quot;nyt_state_data_downloaded.csv&quot;)</code></pre>
</div>
<div id="further-explore-the-data-using-view-before-manipulation-with-dplyr-verbs." class="section level3" number="3.2.3">
<h3><span class="header-section-number">3.2.3</span> Further explore the data using View() before manipulation with dplyr verbs.</h3>
<p>Aside from printing the tibble by simply typing its name (<code>nyt_state_data</code>) we can use <code>View</code> (note the capital <em>V</em>) to view the data in a new window and interact with it in a more hands-on way. <code>View()</code> can be slow as the number of observations rises, but 40,000-ish shouldn’t be too bad. <code>View()</code> allows you to sort the data by values in the columns. We can sort the data by state in the <code>View()</code> window to confirm that the data are, in fact, cumulative: cases and deaths only increase.</p>
<pre class="r"><code>View(nyt_state_data)</code></pre>
<p>Here are some useful base-R commands for describing the basic aspects of the data.</p>
<pre class="r"><code>nrow(nyt_state_data) #How many rows?</code></pre>
<pre><code>## [1] 48838</code></pre>
<pre class="r"><code>ncol(nyt_state_data) #How many columns?</code></pre>
<pre><code>## [1] 5</code></pre>
<pre class="r"><code>dim(nyt_state_data) #Get the table&#39;s dimensions, i.e., number of rows and columns.</code></pre>
<pre><code>## [1] 48838     5</code></pre>
<pre class="r"><code>names(nyt_state_data) #Return the names of the variables.</code></pre>
<pre><code>## [1] &quot;date&quot;   &quot;state&quot;  &quot;fips&quot;   &quot;cases&quot;  &quot;deaths&quot;</code></pre>
<pre class="r"><code>str(nyt_state_data) #Returns information about each variable&#39;s type (i.e., character vs numeric)</code></pre>
<pre><code>## spec_tbl_df [48,838 × 5] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ date  : Date[1:48838], format: &quot;2020-01-21&quot; &quot;2020-01-22&quot; ...
##  $ state : chr [1:48838] &quot;Washington&quot; &quot;Washington&quot; &quot;Washington&quot; &quot;Illinois&quot; ...
##  $ fips  : chr [1:48838] &quot;53&quot; &quot;53&quot; &quot;53&quot; &quot;17&quot; ...
##  $ cases : num [1:48838] 1 1 1 1 1 1 1 1 1 2 ...
##  $ deaths: num [1:48838] 0 0 0 0 0 0 0 0 0 0 ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   date = col_date(format = &quot;&quot;),
##   ..   state = col_character(),
##   ..   fips = col_character(),
##   ..   cases = col_double(),
##   ..   deaths = col_double()
##   .. )
##  - attr(*, &quot;problems&quot;)=&lt;externalptr&gt;</code></pre>
</div>
</div>
</div>
<div id="explore-the-nyt-covid-19-data-using-dplyr" class="section level1" number="4">
<h1><span class="header-section-number">4</span> Explore the NYT COVID-19 data using dplyr</h1>
<p>In this section, I’ll introduce common dplyr verbs. We’ll first go through each verb one by one. Then, we’ll put them together in a sequence.</p>
<div id="essential-dplyr-verbs" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Essential dplyr verbs</h2>
<p>The seven dplyr verbs I use the most are <code>mutate()</code>, <code>filter()</code>, <code>select()</code>, <code>arrange()</code>, <code>group_by()</code>, <code>summarise()</code>, and <code>left_join()</code>:</p>
<ul>
<li><code>mutate()</code> adds new variables (or columns) that can be functions of existing variables.</li>
<li><code>filter()</code> is essentially a subset operator. It picks rows based on their values.</li>
<li><code>select()</code> selects variables (or columns) based on their names. It can also be thought of as a subset operator by column rather than by row.</li>
<li><code>arrange()</code> sorts data. It orders the rows of a data frame by the values of selected columns. The default behavior is to sort ascending, meaning the lowest value will be on top. Use <code>desc()</code> within the <code>arrange()</code> function to sort descending. Importantly, <code>arrange()</code> will sort by group if data are grouped (below).</li>
<li><code>group_by()</code> groups the table by a variable. <code>group_by()</code> is often but not always used with <code>summarise()</code>. When the two are used together, the result is akin to a pivot table in Excel.</li>
<li><code>summarise()</code>, when used after <code>group_by()</code>, collapses the data, with rows corresponding to combinations of the grouping variables. And a new variable can be created within the <code>summarise()</code> function akin to a <code>mutate()</code>. Note that <code>summarise()</code> can also be used if data are not grouped. It can be used to compute a column-wise summary (e.g., mean, median, max) but will keep the dataset in its original form (i.e., not collapsed).</li>
<li><code>left_join()</code> joins two tables together. It’s like a vlookup in Excel or, as the name implies, a JOIN in SQL. It’s distinct from the other verbs in this list in that it is a <a href="https://dplyr.tidyverse.org/articles/two-table.html">two-table verb</a>. There are <a href="https://dplyr.tidyverse.org/reference/join.html">other types of joins</a>, but I almost always use <code>left_join()</code>. A left join, specifically, keeps all of the values of the first datset and only those of the second dataset which correspond to the rows containing with a key common to the first object. In the below set of examples, <code>left_join</code> isn’t used. It is used in subsequent tutorials.</li>
</ul>
<p>There are <a href="https://github.com/rstudio/cheatsheets/blob/master/data-transformation.pdf">several other</a> verbs within dplyr, but many, perhaps most, data-wrangling tasks can be done with just these seven tools.</p>
<p>(For the record, <code>filter()</code>, <code>arrange()</code>, <code>select()</code>, <code>mutate()</code>, and <code>summarise()</code> are considered to be the <a href="https://r4ds.had.co.nz/transform.html#introduction-2">five key dplyr functions</a>. I’ve added <code>group_by()</code> and <code>left_join()</code> because I use them so often.)</p>
</div>
<div id="mutate" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> mutate</h2>
<p>For a demo of <code>mutate()</code>, let’s create a new variable called <code>cases_plus_1</code>, which is simply the number of cases plus 1. The first argument inside the <code>mutate()</code> call is the object to be operated on. And the second argument creates the new variable as a function of the old variable and, in this example, the number 1.</p>
<pre class="r"><code>nyt_state_data_2 = mutate(nyt_state_data, cases_plus_1 = cases+1)</code></pre>
<p>Adding the number 1 to the <code>cases</code> variable works because <code>cases</code> is a <strong>numeric</strong> variable. If <code>cases</code> were a <strong>character</strong> variable, it would not work.</p>
<pre class="r"><code>class(nyt_state_data$cases)</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<p>Now let’s try the same thing but written with the pipe (<code>%&gt;%</code>) operator. As mentioned above, the <a href="https://r4ds.had.co.nz/pipes.html">pipe</a> brings the object out of the parentheses to focus on the action-oriented part of the function, making it easier to read.</p>
<pre class="r"><code>nyt_state_data_2_pipe = nyt_state_data %&gt;% 
  mutate(cases_plus_1 = cases+1)</code></pre>
<p>Check our work by printing each one. They should be the same. Note the new column, <code>cases_plus_1</code>, in the objects <code>nyt_state_data_2</code> and <code>nyt_state_data_2_pipe</code>.</p>
<pre class="r"><code>nyt_state_data_2</code></pre>
<pre><code>## # A tibble: 48,838 × 6
##    date       state      fips  cases deaths cases_plus_1
##    &lt;date&gt;     &lt;chr&gt;      &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;        &lt;dbl&gt;
##  1 2020-01-21 Washington 53        1      0            2
##  2 2020-01-22 Washington 53        1      0            2
##  3 2020-01-23 Washington 53        1      0            2
##  4 2020-01-24 Illinois   17        1      0            2
##  5 2020-01-24 Washington 53        1      0            2
##  6 2020-01-25 California 06        1      0            2
##  7 2020-01-25 Illinois   17        1      0            2
##  8 2020-01-25 Washington 53        1      0            2
##  9 2020-01-26 Arizona    04        1      0            2
## 10 2020-01-26 California 06        2      0            3
## # … with 48,828 more rows
## # ℹ Use `print(n = ...)` to see more rows</code></pre>
<pre class="r"><code>nyt_state_data_2_pipe</code></pre>
<pre><code>## # A tibble: 48,838 × 6
##    date       state      fips  cases deaths cases_plus_1
##    &lt;date&gt;     &lt;chr&gt;      &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;        &lt;dbl&gt;
##  1 2020-01-21 Washington 53        1      0            2
##  2 2020-01-22 Washington 53        1      0            2
##  3 2020-01-23 Washington 53        1      0            2
##  4 2020-01-24 Illinois   17        1      0            2
##  5 2020-01-24 Washington 53        1      0            2
##  6 2020-01-25 California 06        1      0            2
##  7 2020-01-25 Illinois   17        1      0            2
##  8 2020-01-25 Washington 53        1      0            2
##  9 2020-01-26 Arizona    04        1      0            2
## 10 2020-01-26 California 06        2      0            3
## # … with 48,828 more rows
## # ℹ Use `print(n = ...)` to see more rows</code></pre>
<p>Note, also that two new variables can be created in the same <code>mutate()</code> call. Each new variable is separated by a comma. For those familiar with SAS, this begins to look like a SAS data step.</p>
<pre class="r"><code>nyt_state_data_2vars  = nyt_state_data %&gt;% 
  mutate(
    cases_plus_1 = cases+1,
    cases_plus_2 = cases+2
    )
nyt_state_data_2vars</code></pre>
<pre><code>## # A tibble: 48,838 × 7
##    date       state      fips  cases deaths cases_plus_1 cases_plus_2
##    &lt;date&gt;     &lt;chr&gt;      &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;
##  1 2020-01-21 Washington 53        1      0            2            3
##  2 2020-01-22 Washington 53        1      0            2            3
##  3 2020-01-23 Washington 53        1      0            2            3
##  4 2020-01-24 Illinois   17        1      0            2            3
##  5 2020-01-24 Washington 53        1      0            2            3
##  6 2020-01-25 California 06        1      0            2            3
##  7 2020-01-25 Illinois   17        1      0            2            3
##  8 2020-01-25 Washington 53        1      0            2            3
##  9 2020-01-26 Arizona    04        1      0            2            3
## 10 2020-01-26 California 06        2      0            3            4
## # … with 48,828 more rows
## # ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
<div id="filter" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> filter</h2>
<p>What if we only care about one state? Use <code>filter()</code> to subset values to Michigan. Again, we’ll do this with and without the pipe operator.</p>
<pre class="r"><code>nyt_state_data_mi = filter(nyt_state_data, state == &quot;Michigan&quot;)

nyt_state_data_mi_pipe = nyt_state_data %&gt;% 
  filter(state == &quot;Michigan&quot;)</code></pre>
<p>A double equals sign, <code>==</code>, is like asking the question <em>is this equal to?</em>. <code>filter()</code> evaluates where the statement, <code>state == "Michigan"</code>, is true and returns rows with those values.</p>
<p>The number of observations decreased, as we’d expect. There are now 875 observations (at this writing).</p>
<pre class="r"><code>nrow(nyt_state_data_mi)</code></pre>
<pre><code>## [1] 875</code></pre>
<pre class="r"><code>nrow(nyt_state_data_mi_pipe)</code></pre>
<pre><code>## [1] 875</code></pre>
</div>
<div id="select" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> select</h2>
<p>Let’s use <code>select()</code> to grab only the <em>date</em> variable. The syntax is to simply state the columns we want.</p>
<p>Side-note: <code>select()</code> is used by some other packages. To tell R that we want to use the <code>select()</code> function from <strong>dplyr</strong>, specifically, we write <code>dplyr::select()</code>. We can use this syntax for any dplyr verb, e.g. <code>dplyr::mutate()</code> or <code>dplyr::filter()</code>, but <code>select()</code> is the only one where I’ve run into trouble with ambiguity, so I usually leave it off the other ones. The non-piped version:</p>
<pre class="r"><code>date = dplyr::select(nyt_state_data, date)</code></pre>
<p>And the piped version:</p>
<pre class="r"><code>date_pipe = nyt_state_data %&gt;% 
  dplyr::select(date)</code></pre>
<p>Confirm that there’s just one variable using <code>dim(date_pipe)</code> or <code>ncol()</code>.</p>
<pre class="r"><code>dim(date_pipe) #dimensions</code></pre>
<pre><code>## [1] 48838     1</code></pre>
<pre class="r"><code>ncol(date_pipe) #number of columns</code></pre>
<pre><code>## [1] 1</code></pre>
<p>There are several <a href="https://dplyr.tidyverse.org/reference/select.html">helpers</a> that make <code>select()</code> easy to work with. Maybe we want all variables except for the number of deaths:</p>
<pre class="r"><code>nyt_state_data_nodeaths = nyt_state_data %&gt;% 
  dplyr::select(everything(), -deaths)
names(nyt_state_data)</code></pre>
<pre><code>## [1] &quot;date&quot;   &quot;state&quot;  &quot;fips&quot;   &quot;cases&quot;  &quot;deaths&quot;</code></pre>
<pre class="r"><code>names(nyt_state_data_nodeaths)</code></pre>
<pre><code>## [1] &quot;date&quot;  &quot;state&quot; &quot;fips&quot;  &quot;cases&quot;</code></pre>
</div>
<div id="arrange" class="section level2" number="4.5">
<h2><span class="header-section-number">4.5</span> arrange</h2>
<p>Arrange does not change values of the dataset. It just sorts the data. As a reminder, the NYT data include <em>cumulative</em> cases and <em>cumulative</em> deaths on that day in that state. We might also be interested in <em>incident</em> (i.e., new) cases or deaths by state. Let’s use arrange to help calculate daily cases and deaths using the <code>lag()</code> function.</p>
<p>In this code chunk, we’ll combine a few operations sequentially using the pipe, foregoing the nested parentheses approach. When many data-manipulation tasks are chained together, the value of the pipe becomes especially evident. From now on, I’ll adopt the <a href="http://varianceexplained.org/r/teach-tidyverse/">teach-the-tidyverse-first</a> philosophy and stick to its conventions, including the pipe.</p>
</div>
<div id="group_by" class="section level2" number="4.6">
<h2><span class="header-section-number">4.6</span> group_by</h2>
<p>This code also uses <code>group_by()</code>, which does not sort the data, but it tells R to do any subsequent calculations “by group.”</p>
<p><u>Bonus question</u>:</p>
<ul>
<li><p>For this calculation, why is it better to <code>group_by(state)</code> and then arrange by date (i.e.: <code>group_by(state) %&gt;% arrange(date)</code>) before the <code>mutate()</code> rather than an alternative method which could be to forego the grouping and simply arrange by state and then by state (<code>arrange(state, date)</code>)? Try testing both ways and see what the value of the <code>cases_cumul_day_before</code> variable is on the first day of the data for a particular state.</p></li>
<li><p>It’s missing (correctly) when we first <code>group_by()</code>. In contrast, when we use <code>arrange(state, date)</code> without grouping, on the first day of data for a given state, <code>cases_cumul_day_before</code> takes the last day of data for its neighboring state in the alphabet. The <code>lag()</code> function doesn’t know that it shouldn’t take values from a different state. When we use <code>group_by</code>, the subsequent <code>mutate()</code> operates on each state as its own silo, which is what we want in this calculation.</p></li>
</ul>
<p>Note, I’m creating a new dataset called <code>nyt_state_wrangle</code>. I tend to add a <code>_wrangle</code> to the name of datasets I’ve made significant changes to. (Tangent: <a href="https://en.wikipedia.org/wiki/Data_wrangling">Wikipedia page</a> on origins of the term data wrangling).</p>
<pre class="r"><code>nyt_state_wrangle = nyt_state_data %&gt;% 

  #To calculate incident deaths, we will subtract the number of cumulative deaths on one day from the day before.
  #So let&#39;s group the data by state and then sort by date. Note it will default sort to ascending, meaning the earliest days will be on top.
  group_by(state) %&gt;% 
  arrange(date) %&gt;% 
  #Then calculate the number of incident deaths and incident cases on that day by subtracting the corresponding value from the day before.
  #Calculate the value from the day before using the lag() function, which grabs the value of one row up the data.
  #(We could have equivalently sorted descending and then used the lead() function.)
  #To explicitly differentiate between cumulative and incident deaths, let&#39;s rename the cases and deaths variables first. 
  rename(
    cases_cumul = cases,
    deaths_cumul = deaths
  ) %&gt;% 
  mutate(
    cases_cumul_day_before = lag(cases_cumul),
    cases_incident = cases_cumul - cases_cumul_day_before,
    
    deaths_cumul_day_before = lag(deaths_cumul),
    deaths_incident = deaths_cumul - deaths_cumul_day_before
  ) %&gt;% 
  ungroup() %&gt;% 
  #For visual convenience, now sort the data by state by date
  arrange(state, date)

nyt_state_wrangle</code></pre>
<pre><code>## # A tibble: 48,838 × 9
##    date       state   fips  cases_cumul deaths…¹ cases…² cases…³ death…⁴ death…⁵
##    &lt;date&gt;     &lt;chr&gt;   &lt;chr&gt;       &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
##  1 2020-03-13 Alabama 01              6        0      NA      NA      NA      NA
##  2 2020-03-14 Alabama 01             12        0       6       6       0       0
##  3 2020-03-15 Alabama 01             23        0      12      11       0       0
##  4 2020-03-16 Alabama 01             29        0      23       6       0       0
##  5 2020-03-17 Alabama 01             39        0      29      10       0       0
##  6 2020-03-18 Alabama 01             51        0      39      12       0       0
##  7 2020-03-19 Alabama 01             78        0      51      27       0       0
##  8 2020-03-20 Alabama 01            106        0      78      28       0       0
##  9 2020-03-21 Alabama 01            131        0     106      25       0       0
## 10 2020-03-22 Alabama 01            157        0     131      26       0       0
## # … with 48,828 more rows, and abbreviated variable names ¹​deaths_cumul,
## #   ²​cases_cumul_day_before, ³​cases_incident, ⁴​deaths_cumul_day_before,
## #   ⁵​deaths_incident
## # ℹ Use `print(n = ...)` to see more rows</code></pre>
<div id="group_by-continued" class="section level3" number="4.6.1">
<h3><span class="header-section-number">4.6.1</span> group_by (continued)</h3>
<p><code>group_by()</code> is often but not always used in combination with <code>summarise()</code>. We can use <code>group_by()</code> without <code>summarise()</code> to extract the total number of cases and deaths for each state, as the last day of data for each state contains the cumulative total.In the next code chunk, we’ll calculate the same cumulative total using the incident totals calculated above.</p>
<p>To incorporate our changes to the data modified above, first set the new dataset (<code>nyt_last_day_by_state</code>) equal to <code>nyt_state_wrangle</code>.</p>
<pre class="r"><code>nyt_last_day_by_state = nyt_state_wrangle %&gt;% 
  arrange(desc(date)) %&gt;% #Use desc() to sort it by date descending, meaning the most recent day will be on the top of the dataset.
  group_by(state) %&gt;% 
  slice(1) #The number 1 grabs the top row

nyt_last_day_by_state</code></pre>
<pre><code>## # A tibble: 56 × 9
## # Groups:   state [56]
##    date       state        fips  cases…¹ death…² cases…³ cases…⁴ death…⁵ death…⁶
##    &lt;date&gt;     &lt;chr&gt;        &lt;chr&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
##  1 2022-08-01 Alabama      01     1.42e6   19891  1.42e6       0   19891       0
##  2 2022-08-01 Alaska       02     2.87e5    1270  2.87e5       0    1270       0
##  3 2022-08-01 American Sa… 60     7.47e3      33  7.47e3       0      33       0
##  4 2022-08-01 Arizona      04     2.20e6   30768  2.20e6       0   30768       0
##  5 2022-08-01 Arkansas     05     9.05e5   11719  9.04e5     582   11719       0
##  6 2022-08-01 California   06     1.07e7   93651  1.07e7   13280   93613      38
##  7 2022-08-01 Colorado     08     1.61e6   13198  1.60e6    2233   13194       4
##  8 2022-08-01 Connecticut  09     8.55e5   11102  8.55e5     352   11102       0
##  9 2022-08-01 Delaware     10     2.95e5    3024  2.94e5     867    3024       0
## 10 2022-08-01 District of… 11     1.63e5    1364  1.63e5     173    1364       0
## # … with 46 more rows, and abbreviated variable names ¹​cases_cumul,
## #   ²​deaths_cumul, ³​cases_cumul_day_before, ⁴​cases_incident,
## #   ⁵​deaths_cumul_day_before, ⁶​deaths_incident
## # ℹ Use `print(n = ...)` to see more rows</code></pre>
<pre class="r"><code>#How many rows does the data have? The data should contain one row for each state or territory, since we grouped by state.
nrow(nyt_last_day_by_state)</code></pre>
<pre><code>## [1] 56</code></pre>
<p>To see the difference between using and not using <code>group_by()</code>, try this code chunk. It will just grab the top row.</p>
<pre class="r"><code>nyt_last_day  = nyt_state_wrangle %&gt;% 
  arrange(desc(date)) %&gt;% 
#  group_by(state) %&gt;% #This comments out the code so this part doesn&#39;t run.
  slice(1) #The number 1 grabs the top row

nrow(nyt_last_day)</code></pre>
</div>
<div id="group_by-and-summarise" class="section level3" number="4.6.2">
<h3><span class="header-section-number">4.6.2</span> group_by and summarise</h3>
<p>Now, let’s use <code>group_by()</code> and <code>summarise()</code> together. The syntax of <code>summarise()</code> is similar to <code>mutate()</code> in that it creates a new variable with each equals sign. As with <code>mutate()</code>, several new variables can be created in a single <code>summarise()</code>, with each equality separated by a comma.</p>
<p>Let’s calculate three group-by summaries:</p>
<ul>
<li>the average number of incident cases per day by state,</li>
<li>the cumulative number of cases by state (way 1) by summing incident cases,</li>
<li>the cumulative number of cases by state (way 2) by taking the maximum value of the number of cumulative cases.</li>
</ul>
<p>Note that we have already found the cumulative number of cases above using <code>arrange()</code>, <code>group_by()</code>, and <code>slice()</code>. So here are two more options.</p>
<p><code>sum()</code>, <code>mean()</code>, and <code>max()</code> are arithmetic functions in base R. In these functions, it’s good practice state <code>na.rm=TRUE</code> unless there’s a good reason not to. This argument stands for “remove missings equals true”. The default behavior of these arithmetic functions is to include missing values in the calculation (<code>na.rm = FALSE</code>), which means the arithmetic summary will also return a missing (2+missing=missing), and that is typically not the desired outcome.</p>
<pre class="r"><code>names(nyt_state_wrangle) #To remember the variable names.</code></pre>
<pre><code>## [1] &quot;date&quot;                    &quot;state&quot;                  
## [3] &quot;fips&quot;                    &quot;cases_cumul&quot;            
## [5] &quot;deaths_cumul&quot;            &quot;cases_cumul_day_before&quot; 
## [7] &quot;cases_incident&quot;          &quot;deaths_cumul_day_before&quot;
## [9] &quot;deaths_incident&quot;</code></pre>
<pre class="r"><code>nyt_cases_summary = nyt_state_wrangle %&gt;% 
  group_by(state) %&gt;% 
  summarise(
    cases_incident_average = mean(cases_incident, na.rm=TRUE),
    cases_cumul_way1 = sum(cases_incident, na.rm=TRUE),
    cases_cumul_way2 = max(cases_cumul, na.rm=TRUE)
    )

dim(nyt_cases_summary)</code></pre>
<pre><code>## [1] 56  4</code></pre>
<pre class="r"><code>nyt_cases_summary</code></pre>
<pre><code>## # A tibble: 56 × 4
##    state                cases_incident_average cases_cumul_way1 cases_cumul_way2
##    &lt;chr&gt;                                 &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;
##  1 Alabama                              1635.           1424405          1424411
##  2 Alaska                                329.            286792           286793
##  3 American Samoa                         23.9             7470             7471
##  4 Arizona                              2393.           2196428          2196429
##  5 Arkansas                             1036.            904512           904513
##  6 California                          11658.          10713332         10713333
##  7 Colorado                             1827.           1605856          1605858
##  8 Connecticut                           976.            854933           854934
##  9 Delaware                              338.            294907           294908
## 10 District of Columbia                  186.            162691           162692
## # … with 46 more rows
## # ℹ Use `print(n = ...)` to see more rows</code></pre>
<p>The number of rows is equal to the number of groups (55; some territories are included). The data used to include date, but we have collapsed over date here. When <code>group_by()</code> and <code>summarise()</code> are used together, the number of rows in the data will be equal to the number of groups.</p>
<p>The number of variables is four: the grouping variable (<code>state</code>) and each of the summary measures we calculated for each state.</p>
<p>Note that the two cumulative values differ slightly for some of the states. This discrepancy could be explained by the <a href="https://github.com/nytimes/covid-19-data/blob/master/PROBABLE-CASES-NOTE.md">nuances of the NYT’s reporting system</a>, which contains a mix of both probable and confirmed cases. The most trustworthy value is probably <code>cases_cumul_way2</code>, which takes the most recent reported cumulative value.</p>
</div>
<div id="group_by-and-summarise-continued" class="section level3" number="4.6.3">
<h3><span class="header-section-number">4.6.3</span> group_by and summarise (continued)</h3>
<p>Another application of the group-by-summarise syntax is if one wants to calculate overall summary estimates of the whole dataset. For example, as a double check, we can check to confirm the data we’re using lines up with what the NYT is reporting on their website for the total number of cumulative cases to date.</p>
<p>At this writing (8/2/22), NYT reports a total of ~91.3 million cases (<a href="https://www.nytimes.com/interactive/2021/us/covid-cases.html" class="uri">https://www.nytimes.com/interactive/2021/us/covid-cases.html</a>). Can we reproduce that? To summarize over the whole dataset, create a dummy variable with the same value for every observation and then sum over that variable.</p>
<pre class="r"><code>nyt_cases_overall = nyt_state_wrangle %&gt;% 
  group_by(state) %&gt;% 
  summarise(cases_cumul = max(cases_cumul, na.rm=TRUE)) %&gt;% 
  ungroup() %&gt;% 
  mutate(dummy=1) %&gt;%
  group_by(dummy) %&gt;% 
  summarise(cases_cumul = sum(cases_cumul, na.rm=TRUE))
    

nyt_cases_overall</code></pre>
<pre><code>## # A tibble: 1 × 2
##   dummy cases_cumul
##   &lt;dbl&gt;       &lt;dbl&gt;
## 1     1    91296149</code></pre>
<p>Confirmed. The total cumulative number of cases at this writing (8/2/22) is 91,296,149, which is about what they’re reporting on their website today (~91.3 million). Note this total includes the cases from Guam, Northern Mariana Islands, Puerto Rico, and the Virgin Islands.</p>
<p><img src="images/total-cases-nyt-aug-2-2022.png" width="500" /></p>
</div>
</div>
<div id="all-together-now-in-an-example-using-case_when" class="section level2" number="4.7">
<h2><span class="header-section-number">4.7</span> All together now in an example using <code>case_when()</code></h2>
<p><strong>Goal</strong>: calculate the total number of deaths in each state in the <a href="https://en.wikipedia.org/wiki/Great_Lakes_region">Great Lakes Region</a>: Illinois, Indiana, Michigan, Minnesota, New York, Ohio, Pennsylvania, and Wisconsin. Do it all in one sequential pipe. In this code, I’ll introduce the <a href="https://dplyr.tidyverse.org/reference/case_when.html"><code>case_when()</code></a> function, which is a useful way to create new variables conditional on values of other variables.</p>
<p>Also note the use of the “or” operator, <code>|</code>.</p>
<p>Filtering the data to the subset of states in the Great Lakes Region could be done a few different ways. With complicated subsets, I prefer to create an indicator variable and then filter values based on that indicator variable, rather than putting all of the subset information into the <code>filter()</code> function.</p>
<p>So the code below uses <code>mutate()</code> to create a variable called <code>great_lakes</code>, which is equal to 1 if the state is in the Great Lakes region and 0 if not.</p>
<p>I also define this variable, <code>great_lakes_alt</code>, an alternative way, which is more concise but arguably less readable, using the <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/match.html"><code>%in%</code></a> operator. That operator returns TRUE if an element belongs to a vector. A quick example to show this:</p>
<pre class="r"><code>x=c(1,2,3,4,5)
5%in%x</code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r"><code>6%in%x</code></pre>
<pre><code>## [1] FALSE</code></pre>
<pre class="r"><code>deaths_cumul_by_state_greatlakes = nyt_state_wrangle %&gt;% 
  mutate(
    #If the condition is met, set the value to 1. If not -- confusingly expressed by TRUE -- set it to 0.
    great_lakes = case_when(
      state == &quot;Illinois&quot; |
      state == &quot;Indiana&quot; |
      state == &quot;Michigan&quot; |
      state == &quot;Minnesota&quot; |
      state == &quot;New York&quot; |
      state == &quot;Ohio&quot; |
      state == &quot;Pennsylvania&quot; |
      state == &quot;Wisconsin&quot; ~ 1,
      TRUE ~ 0),  #The parentheses closes this case_when function.
    #The comma outside the parentheses implies we have another variable to be created in the mutate function
    
    #Alternative way using the %in% operator:A more concise way to state that may arguably be less readable is to use %in%    
    #The case_when function assigns a 1 wherever it&#39;s true.
    great_lakes_alt = case_when(
      state %in% c(
        &quot;Illinois&quot;, &quot;Indiana&quot;, &quot;Michigan&quot;, 
        &quot;Minnesota&quot;, &quot;New York&quot;, &quot;Ohio&quot;, 
        &quot;Pennsylvania&quot;, &quot;Wisconsin&quot;
        ) ~ 1,
    TRUE ~0)
  ) %&gt;% 
  
  filter(great_lakes==1) %&gt;% 
  group_by(state) %&gt;% 
  summarise(
    deaths_cumul = max(deaths_cumul, na.rm=TRUE)
  )</code></pre>
<p>It should be a small dataset (8 rows (one for each state) by 2 columns (<code>state</code> and <code>deaths_cumul</code>)), so let’s print it to check:</p>
<pre class="r"><code>deaths_cumul_by_state_greatlakes</code></pre>
<pre><code>## # A tibble: 8 × 2
##   state        deaths_cumul
##   &lt;chr&gt;               &lt;dbl&gt;
## 1 Illinois            38888
## 2 Indiana             24106
## 3 Michigan            37428
## 4 Minnesota           13293
## 5 New York            69628
## 6 Ohio                39035
## 7 Pennsylvania        46205
## 8 Wisconsin           14936</code></pre>
<p>That concludes this tutorial. In our next tutorial, we’ll continue using dplyr and we’ll introduce <strong>tidycensus</strong>, <strong>mapview</strong>, and <strong>ggplot</strong> to use census data to visualize Covid-19 incidence per population.</p>
</div>
</div>

<br>
<br>
<p>Copyright &copy; 2022 Michael D. Garber </p>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
